import Foundation

enum TextModel: String {
//    case email = "teste@movies.com.br"
    case email = "teste"
    case password = "1234"
    case fontRubikLight = "Rubik-Light"
    case fontRubikRegular = "Rubik-Regular"
    case fontRubikMedium = "Rubik-Medium"
    case fontRubikBold = "Rubik-Bold"
    case okey = "OK"
    case error = "Erro"
    case camposInvalid = "Campos Inválidos."
    case loginInvalid = "Login Inválido."
    case emailAndPasswordInvalid = "Email ou Senha incorretos."
    case main = "Main"
    case home = "Home"
    case colorBlack = "Black"
    case logoPlayMovies = "LogoPlayMovies"
    case nameEmail = "Email"
    case colorWhite = "White"
    case colorGrayLight = "GrayLight"
    case colorGrayMedium = "GrayMedium"
    case envelope = "envelope"
    case namePassword = "Senha"
    case lock = "lock"
    case eyeFill = "eye.fill"
    case colorPinkMedium = "PinkMedium"
    case entrar = "ENTRAR"
    case circleFill = "x.circle.fill"
    case colorRedMedium = "RedMedium"
    case credentialIncorrect = "Credenciais Incorretas"
    case namefatalError = "init(coder:) has not been implemented"
    case eyeSlashFill = "eye.slash.fill"
}
